name: Specmatic Insights Central Contract Repo Report

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Generate central contract repo report
        run: |
          docker run -v "$(pwd):/central-contract-repo:rw" \
            --entrypoint /bin/sh specmatic/specmatic \
            -c "cd /central-contract-repo && specmatic central-contract-repo-report"

      - name: Check URL Redirect
        run: |
          curl -I -L -o /dev/null -s -w "%{http_code} %{url_effective}\n" https://insights.specmatic.io

      - name: Run Specmatic Insights Github Build Reporter
        run: |
          docker run \
            -v ${{ github.workspace }}:/workspace \
            specmatic/specmatic-insights-github-build-reporter:latest \
              --specmatic-insights-host https://insights.specmatic.io \
              --specmatic-reports-dir /workspace/build/reports/specmatic \
              --org-id ${{ secrets.SPECMATIC_ORG_ID }} \
              --branch-name ${{ github.ref_name }} \
              --repo-name ${{ github.event.repository.name }} \
              --repo-id ${{ github.repository_id }} \
              --repo-url ${{ github.event.repository.html_url }}
